### ISSUE TITLE
Passing `ref` to `Collapse`

### ISSUE THREAD

**Issue by fabien-ml** [smastrom/solid-collapse#2]
Hi not sure if it will help, but you can use [mergeRefs](https://github.com/solidjs-community/solid-primitives/tree/main/packages/refs#mergeRefs) from solid-primitives to allow user to pass ref and also use your internal ref.

**Comment by smastrom** [comment]
Hi @fabien-ml, first of all sorry for getting back to you so late. I didn't know about the existence of `mergeProps`. I will indeed start using it in other projects now that I know about its existence thanks to you. That said, for `solid-collapse` I would like to avoid to add any deps since I always wanted to keep it super lightweight and dependency-free.

However, if Solid will release a similar native feature, even in read-only mode like Vue's [defineExpose](https://vuejs.org/api/sfc-script-setup.html#defineexpose) (which I implemented in my other package [vue-collapsed](https://github.com/smastrom/vue-collapsed)) please let me know or feel free to submit a PR.

Thank you again,

Simone
